cpanel:
  version: "1.0"
  settings:
    git:
      enable: true
      repository: "https://github.com/Vextotem/Ceeflix-.git"
      branch: "main"
      commit_on_push: true
      post_update_hook: "/scripts/post-update.sh"
    deployment:
      enable: true
      script: "/home/username/scripts/deploy.sh"
      trigger_on_push: true
      auto_pull_on_push: true
      notification:
        enable: true
        email: "emmaolt0@gmail.com"
        subject: "New commit pushed to Ceeflix repository"
        body: "A new commit has been pushed to the Ceeflix repository, and the deployment has been triggered."

  logging:
    enable: true
    log_file: "/var/log/cpanel/git-deployment.log"
    level: "info"
