[[redirects]]
from = "/series/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/movie/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/watch/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
